# This file is in TOML format.
# See: https://github.com/toml-lang/toml

tasks = [
  "rta_complete",
  "bcl2fastq",
  "fastqc",
  "create_checksum_manifest",
#  "rsync_to_archive",
  "mytardis_upload"
]

run_storage_base = "/data/illumina"

# When false, run directories without read/write permissions throw an ERROR log
# When true, they are skipped with an INFO log message
skip_bad_permissions = true

# Failure notification frequency, minutes (1440 min = daily)
# When in --quiet mode, ERROR messages for failed runs
# will only be output to the `autoprocess_notify` logger
# every `notify_frequency` minutes. This is particularly useful
# for email handlers when running under cron.
notify_frequency = 1440

[bcl2fastq]
nice                          = true
# runfolder-dir                 = /data/illumina/my_run
# output-dir                    = "{run_path}/{run_id}.bcl2fastq"
# bcl2fastq will run inside a Docker container if docker_image is specified
# docker_image                  = "genomicpariscentre/bcl2fastq2:2.19.0.316"
binary_path                   = "/usr/local/bin/bcl2fastq"

  [bcl2fastq.args]
  # These options map directly to bcl2fastq commandline options, eg:
  #   barcode-mismatches = 1
  #     becomes
  #   --barcode-mismatches 1
  # Boolean values of true/false just add the --flag without a value
  barcode-mismatches           = 1
  no-lane-splitting             = true
  minimum-trimmed-read-length   = 0
  mask-short-adapter-reads      = 0
  fastq-compression-level       = 9
  # tiles                         = "s_1_1101"

# [fastqc]
# binary_path = "/software/apps/FastQC/fastqc"

# TODO: Not implemented
# [rta_complete]
# flag_file                     = "{run_path}/RTAComplete.txt"

# TODO: Not implemented
# [create_checksum_manifest]
# algorithms                    = ['md5', 'sha512', 'xxhash']
# manifest_style                = 'sum'
# manifest_style                = 'hashdeep'

[rsync_to_archive]
target_basepath                 = "/data/illumina/archive_test"
# sudo                            = true
# chown                           = "root:root"
args = [
 '--exclude="{run_dir}/Thumbnail_Images/"',
 '--include="*.xml"',
 '--include="*.csv"',
 '--include="*.log"',
 # This line excludes BCL files
 '--exclude="{run_dir}/Data/Intensities/BaseCalls/L0*/"',
]
