# This is the 'location' used by the storage box
storage_base_path: /data/instrument

# The name of the default MyTardis StorageBox to use.
# If in doubt, leave as default.
storage_box_name: default

# Default MyTardis storage mode - upload, staging or shared
storage_mode: upload

# The name of the MyTardis StorageBox where highly available 'live'
# files that need to be served immediately (eg small HTML report files)
# will be uploaded. An S3-style object store is a often a good option.
# These files should never be migrated to tape.
live_storage_box_name: live
# live_storage_box_name: object_store

# The path to the directory with data to
# be uploaded/registerd with MyTardis
path: /data/instrument/some_unique_expt_id_001/

# The path to bcl2fastq output. Uses Pythons str.format method
# with named parameters, where {run_path} is the base path
# of the run (eg --path config option above) and {run_id}
# is the unique ID of the run (eg 130613_SNL177_0029_AH0EPTADXX or
# in the example above, some_unique_expt_id_001)
# Don't forget the double quotes !
bcl2fastq_output_path: "{run_path}/{run_id}.bcl2fastq"

# A list of groups (by name) that will be given ownership of ingested
# experiments. Typically this contains the facility manager group.
experiment_owner_groups:
    - mhtp-facility-managers
    - somegreatgroup

# A list of Python regular expressions matching files to exclude
# matches against the absolute path. 'Hidden' files beginning
# with a period (.) are excluded by default.
# Don't use quotes, and expressions are comma delimited without
# regard to escaping so you can't use commas :/
exclude:
    - '/FastQC\.done$'
    - '/FastQC\.inprogress$'
    - '/LIST$'
    - '/Temp$'
    - '/Temp/.*'
    - 'SampleSheet.csv'
    - '/Basecall_Stats_\w+$'
    - '/Basecall_Stats_\w+/.*'

username: powerfuladmin

# Don't make this config file world readable !
password: ub3rsecre7z!

# The address of the MyTardis server, including :port
url: http://mytardis-server.edu.au:8000

# Should we run FastQC on reads before uploading
# if expected output directory doens't exist ?
run_fastqc: True

# The number of threads to use for some paralell processes
# usually this would be close to the number of cores on the machine
threads: 4

# The path to the FastQC executable
fastqc_bin: /usr/bin/fastqc
