# This is the 'location' used by the storage box
storage_base_path: /data/instrument

# The name of the default MyTardis StorageBox to use.
# If in doubt, leave as default.
storage_box_name: default

# Default MyTardis storage mode - upload, staging or shared
storage_mode: upload

# The name of the MyTardis StorageBox where highly available 'live'
# files that need to be served immediately (eg small HTML report files)
# will be uploaded. An S3-style object store is a often a good option.
# These files should never be migrated to tape.
live_storage_box_name: object_store
# live_storage_box_name: live


# The path to the directory with data to
# be uploaded/registerd with MyTardis
path: /data/instrument/some_unique_expt_id_001/

# The path to bcl2fastq output. Uses Pythons str.format method
# with named parameters, where {run_path} is the base path
# of the run (eg --path config option above) and {run_id}
# is the unique ID of the run (eg 130613_SNL177_0029_AH0EPTADXX or
# in the example above, some_unique_expt_id_001)
# Don't forget the double quotes !
bcl2fastq_output_path: "{run_path}/{run_id}.bcl2fastq"

# A list of groups (by name) that will be given ownership of ingested
# experiments. Typically this contains the facility manager group.
experiment_owner_groups:
  - mhtp-facility-managers
  - somegreatgroup

# A list of Python regular expressions matching files to exclude
# matches against the absolute path. 'Hidden' files beginning
# with a period (.) are excluded by default.
# Don't use quotes, and expressions are comma delimited without
# regard to escaping so you can't use commas :/
exclude:
  - '/FastQC\.done$'
  - '/FastQC\.inprogress$'
  - '/LIST$'
  - '/Temp$'
  - '/Temp/.*'
  - 'SampleSheet.csv'
  - '/Basecall_Stats_\w+$'
  - '/Basecall_Stats_\w+/.*'

username: powerfuladmin

# Don't make this config file world readable !
password: ub3rsecre7z!

# The address of the MyTardis server, including :port
url: http://localhost:8000
# url: http://mytardis-server.edu.au:8000
# url: https://secure.mytardis-server.edu.au

# The path to the certificate of the server when using SSL/TLS, to
# allow it's identity to be verified. You should set this if your MyTardis
# server are uses a self-signed certificate, rather than one signed by a
# certificate authority.
# If you are using a self-signed certificate and the 'certificate' setting
# isn't set, you may set this value to INSECURE (all-caps) to acknowledge that
# you are happy to connect to a server of unverified identity (with the
# possibility of MITM attacks). Using INSECURE is strongly discouraged.
# certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
# certificate: INSECURE
# An empty or missing value default to always verify
# certificate:

# Should we run FastQC on reads before uploading
# if expected output directory doesn't exist ?
run_fastqc: True

# The number of threads to use for some paralell processes
# usually this would be close to the number of cores on the machine
threads: 4

# The path to the FastQC executable
fastqc_bin: /usr/bin/fastqc

# Specifies whether the ingestor should automatically move any existing run
# on the server to 'trash' if it matches the unique run ID of the current run
# This is useful when a run was demultiplexed incorrectly
# (eg errors in SampleSheet.csv) and needs to be ingested again, without
# cluttering the web interface with multiple versions of the same run
replace_duplicate_runs: False
# Username and group name for the 'trash'
trash_user: __trashman__
trash_group: __trashcan__
