# This is the 'location' used by the storage box
storage_base_path: /data/instrument

# The path to the directory with data to
# be uploaded/registerd with MyTardis
path: /data/instrument/some_expt_001/

# A list of Python regular expressions matching files to exclude
# matches against the absolute path. 'Hidden' files beginning
# with a period (.) are excluded by default.
# Don't use quotes, and expressions are comma delimited without
# regard to escaping so you can't use commas :/
exclude:
    - '/FastQC\.done$'
    - '/FastQC\.inprogress$'
    - '/LIST$'
    - '/Temp$'
    - '/Temp/.*'
    - 'SampleSheet.csv'
    - '/Basecall_Stats_\w+$'
    - '/Basecall_Stats_\w+/.*'

username: powerfuladmin

# Don't make this config file world readable !
password: ub3rsecre7z!

# The address of the MyTardis server, including :port
url: http://mytardis-server.edu.au:8000

# upload, staging or shared
storage_mode: upload

# Should we run FastQC on reads before uploading ?
run_fastqc: False

# The number of threads to use for some paralell processes
# usually this would be close to the number of cores on the machine
threads: 4

# The path to the FastQC executable
fastqc_bin: /usr/bin/fastqc
