# this is the 'location' used by the storage box
storage_base_path: /data/instrument

# the path to the directory with data to
# be uploaded/registerd with MyTardis
path: /data/instrument/some_expt_001/

# a list of Python regular expressions matching files to exclude
# matches against the absolute path. 'Hidden' files beginning
# with a period (.) are excluded by default
# don't use quotes, and expressions are comma delimited without
# regard to escaping so you can't use commas :/
exclude:
    - '/FastQC\.done$'
    - '/FastQC\.inprogress$'
    - '/LIST$'
    - '/Temp$'
    - '/Temp/.*'
    - 'SampleSheet.csv'
    - '/Basecall_Stats_\w+$'
    - '/Basecall_Stats_\w+/.*'

experiment_schema:
    # no experiment_type makes it the default
    - url: http://www.tardis.edu.au/schemas/sequencing/illumina/run
    - url: http://www.tardis.edu.au/schemas/sequencing/illumina/demultiplexed_samples
      experiment_type: demultiplexed_samples

dataset_schema:
    # no dataset_type makes it the default
    - url: http://www.tardis.edu.au/schemas/sequencing/illumina/run
    # or we can specify a dataset type
    - url: http://www.tardis.edu.au/schemas/sequencing/raw_reads
      dataset_type: fastq
    - url: http://www.tardis.edu.au/schemas/sequencing/aligned_reads
      dataset_type: bam

datafile_schema:
    - url: http://www.tardis.edu.au/schemas/sequencing/fastq
      datafile_type: fastq
    - url: http://www.tardis.edu.au/schemas/sequencing/fastqc
      datafile_type: fastqc
    - url: http://www.tardis.edu.au/schemas/sequencing/bam
      datafile_type: bam

username: powerfuladmin

# don't make this config file world readable !
password: ub3rsecre7z!

# the address of the MyTardis server, including :port
url: http://mytardis-server.edu.au:8000

# upload, staging or shared
storage_mode: upload
